#! /bin/sh

SAGE_STANDARD=http://www.sagemath.org/packages/standard
SPD_STANDARD=http://spdproject.googlecode.com/files

if [ `uname` = 'Darwin' ]; then
    WGET="curl -O"
else
    WGET="wget -nc"
fi


# SPD minimum:
$WGET $SAGE_STANDARD/termcap-1.3.1.p1.spkg
$WGET $SAGE_STANDARD/zlib-1.2.3.p5.spkg
$WGET $SAGE_STANDARD/readline-6.0.p1.spkg
$WGET $SAGE_STANDARD/python-2.6.4.p7.spkg
$WGET $SPD_STANDARD/ipython-0.9.1.p0.spkg
$WGET $SAGE_STANDARD/cython-0.12.1.spkg

# notebook:
$WGET $SAGE_STANDARD/pexpect-2.0.p4.spkg
$WGET $SAGE_STANDARD/twisted-9.0.p2.spkg
# $WGET $SAGE_STANDARD/twisted-8.1.0.p2.spkg
$WGET $SAGE_STANDARD/setuptools-0.6c9.p0.spkg
# $WGET $SAGE_STANDARD/jinja-1.2.p0.spkg
$WGET $SAGE_STANDARD/jinja2-2.1.1.p0.spkg
$WGET $SAGE_STANDARD/libgpg_error-1.6.p3.spkg
$WGET $SAGE_STANDARD/libgcrypt-1.4.4.p2.spkg
$WGET $SAGE_STANDARD/gnutls-2.2.1.p5.spkg
$WGET $SAGE_STANDARD/python_gnutls-1.1.4.p7.spkg
$WGET $SPD_STANDARD/sagenb-0.8.p3.spkg
# the following packages are not part of sage 4.4.2
# $WGET $SAGE_STANDARD/jquery-1.2.6.p0.spkg
# $WGET $SAGE_STANDARD/jqueryui-1.6r807svn.p0.spkg
# $WGET $SAGE_STANDARD/jsmath-3.6b.p1.spkg
# $WGET $SAGE_STANDARD/tinyMCE-3.2.0.2.p0.spkg
# $WGET $SPD_STANDARD/spd_notebook-3.4.1-5.spkg

# numpy, scipy matplotlib and sympy
$WGET $SAGE_STANDARD/fortran-20100428.spkg
$WGET $SAGE_STANDARD/lapack-20071123.p1.spkg
$WGET $SAGE_STANDARD/blas-20070724.spkg
$WGET $SAGE_STANDARD/atlas-3.8.3.p12.spkg
$WGET $SAGE_STANDARD/numpy-1.3.0.p3.spkg
$WGET $SAGE_STANDARD/scipy-0.7.p4.spkg
$WGET $SAGE_STANDARD/freetype-2.3.5.p2.spkg
$WGET $SAGE_STANDARD/libpng-1.2.35.p1.spkg
$WGET $SAGE_STANDARD/matplotlib-0.99.1.p4.spkg
$WGET $SAGE_STANDARD/sympy-0.6.4.p0.spkg
